"""Anonymous browser-session identifiers used for resource ownership."""

from __future__ import annotations

from uuid import RFC_4122, UUID

from fastapi import HTTPException, Request, status


BROWSER_SESSION_HEADER = "X-SkripsiCheck-Session-ID"
_INVALID_SESSION_DETAIL = (
    f"A valid UUIDv4 is required in the {BROWSER_SESSION_HEADER} header."
)


def parse_browser_session_id(value: str | None) -> UUID:
    """Parse a canonical UUIDv4 generated by ``crypto.randomUUID()``.

    The parser accepts either letter case but rejects braces, URNs, non-v4
    UUIDs, and surrounding whitespace so one session has one stable form.
    """

    if value is None or len(value) != 36:
        raise ValueError("Invalid browser session ID.")
    try:
        parsed = UUID(value)
    except (AttributeError, ValueError) as exc:
        raise ValueError("Invalid browser session ID.") from exc
    if (
        parsed.version != 4
        or parsed.variant != RFC_4122
        or str(parsed) != value.casefold()
    ):
        raise ValueError("Invalid browser session ID.")
    return parsed


def require_browser_session(request: Request) -> UUID:
    """FastAPI dependency returning a validated anonymous session UUID."""

    try:
        return parse_browser_session_id(request.headers.get(BROWSER_SESSION_HEADER))
    except ValueError as exc:
        # Do not reflect the untrusted header value into the response.
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=_INVALID_SESSION_DETAIL,
        ) from exc
